default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: victor
  password: 123456
  database: nepe_references_development

test:
  <<: *default
  database: nepe_references_test

production:
  <<: *default
  database: nepe_references_production
  username: nepe_references
  password: <%= ENV['NEPE_REFERENCES_DATABASE_PASSWORD'] %>
